name: finalize profile repository

on:
  push:
    paths:
      - ".github/workflows/finalize-profile-repo.yml"
  workflow_dispatch:

permissions: write-all

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: Rename repository to match GitHub username
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PATCH "repos/${GITHUB_REPOSITORY}" -f name="Ruthvik-Uttarala"